dist: xenial

sudo: required

services:
- docker

env:
 global:
   - CEPH_VERSION=nautilus
   - KUBE_VERSION=1.15.0-00
   - DOCKER_VERSION=5:18.09.6~3-0
 
script:
- >
  sudo rm -rf debs &&
  sudo mkdir -p debs/packages &&
  sudo apt-get update &&
  sudo apt-get install -y apt-transport-https curl software-properties-common &&
  sudo curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - &&
  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - &&
  sudo curl -fsSL https://download.ceph.com/keys/release.asc | sudo apt-key add - &&
  sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable' &&
  sudo cp kubernetes.list /etc/apt/sources.list.d/ &&
  sudo echo deb https://download.ceph.com/debian-${CEPH_VERSION}/ xenial main | sudo tee /etc/apt/sources.list.d/ceph.list &&
  sudo apt-get clean &&
  sudo apt-get update &&
  sudo chmod +x apt-download.sh &&
  sudo ./apt-download.sh docker-ce=${DOCKER_VERSION}~ubuntu-xenial &&
  sudo ./apt-download.sh docker-compose python-docker python-chardet python-requests &&
  sudo ./apt-download.sh chrony auditd audispd-plugins dnsutils netcat rsync jq git tcpdump net-tools ipvsadm graphviz &&
  sudo ./apt-download.sh ceph-deploy ceph rbd-nbd rbd-mirror radosgw radosgw-agent open-vm-tools nfs-common &&
  sudo ./apt-download.sh kubelet=${KUBE_VERSION} kubectl=${KUBE_VERSION} kubeadm=${KUBE_VERSION} &&
  sudo mv *.deb debs/packages &&
  sudo apt-ftparchive packages debs/packages/. > /tmp/Packages &&
  sudo apt-ftparchive release debs/packages/. > /tmp/Release &&
  sudo cp /tmp/Packages debs/ &&
  sudo cp /tmp/Release debs/

- sudo chmod -R 755 ${PWD}/debs
- docker build -t wise2c/apt-source:$TRAVIS_BRANCH .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push wise2c/apt-source:$TRAVIS_BRANCH
