sudo: required

services:
- docker

before_install:
- docker pull ubuntu:16.04

env:
 global:
   - CEPH_VERSION=nautilus
   - KUBE_VERSION=1.15.0-00
   - DOCKER_VERSION=5:18.09.6~3-0
 
script:
- >
  docker run -t --rm -v ${PWD}/debs:/root/debs -v ${PWD}/kubernetes.list:/root/kubernetes.list ubuntu:16.04 bash -c
  "apt-get update && apt-get install -y apt-transport-https curl software-properties-common &&
   curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - &&
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - &&
   add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable' &&
   cp /root/kubernetes.list /etc/apt/sources.list.d/ &&
   apt-get update &&
   apt-get install -y --download-only docker-ce=${DOCKER_VERSION}~ubuntu-xenial &&
   apt-get install -y --download-only docker-compose python-docker python-chardet python-requests &&
   apt-get install -y --download-only chrony auditd audispd-plugins rsync jq git tcpdump net-tools ipvsadm graphviz &&
   apt-get install -y --download-only kubelet=${KUBE_VERSION} kubectl=${KUBE_VERSION} kubeadm=${KUBE_VERSION} &&
   mv /var/cache/apt/archives/*.deb /root/debs/"

- sudo chmod -R 755 ${PWD}/debs
- docker build -t wise2c/apt-source:$TRAVIS_BRANCH .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push wise2c/apt-source:$TRAVIS_BRANCH
