sudo: required

services:
- docker

before_install:
- docker pull ubuntu:16.04

env:
 global:
   - CEPH_VERSION=nautilus
   - KUBE_VERSION=1.15.0-00
   - DOCKER_VERSION=5:18.09.6~3-0
 
script:
- >
  docker run -t --rm -v ${PWD}/debs:/root/debs -v ${PWD}/kubernetes.list:/etc/apt/sources.list.d/kubernetes.list ubuntu:16.04
  bash -c
  "apt-get update && apt-get install -y apt-transport-https curl &&
   curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - &&
   apt-get update &&
   apt-get install -y --download-only kubelet=${KUBE_VERSION} kubectl=${KUBE_VERSION} kubeadm=${KUBE_VERSION} &&
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - &&
   apt-get install software-properties-common &&
   add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" &&
   apt-get update &&
   apt-get install docker-ce=${DOCKER_VERSION}~ubuntu-xenial

   mv /var/cache/apt/archives/*.deb /root/debs/"

- sudo chmod -R 755 ${PWD}/debs
- docker build -t wise2c/apt-source:$TRAVIS_BRANCH .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push wise2c/apt-source:$TRAVIS_BRANCH
